### ISSUE TITLE
Switching servers

### ISSUE THREAD

**Issue by misiek08** [roblabla/MyLittleProxy#1]
Hello!
I'm working on proxy too, but one of the best features is being able to switch servers that sit behind proxy.
I made array with servers {name: [ip, port], [....]} and trying to switch server on plugin message with data "Connect".
Here's is code, that takes data from packet:

``` js
if(packet.id == 0x3f)
    {
        if(packet.data.toString().substring(2, 9) == 'Connect')
        {
            var server = servers[packet.data.toString().substring(11)];
```

All works, but there comes switching remote connection to new one. I'm stuck at this:

``` js
switching = true;
var oldremote = remoteclient;
var newremote = {
    host: serwer[0],
    port: serwer[1],
    online_mode: false,
    force_username: false,
    username: 'asd',
    password: 'qwe',
};
var newremoteclient = mc.createClient(newremote);
newremoteclient.once('login', function (){
    remoteclient = newremoteclient;
    // oldremote.endSocket();
    switching = false;
});
```

and this produces:

```
Error: ForbiddenOperationException
    at /home/nodeproxy/MyLittleProxy/node_modules/minecraft-protocol/lib/yggdrasil.js:51:23
    at Request.callback (/home/nodeproxy/MyLittleProxy/node_modules/minecraft-protocol/node_modules/superagent/lib/node/index.js:575:3)
    at Request.<anonymous> (/home/nodeproxy/MyLittleProxy/node_modules/minecraft-protocol/node_modules/superagent/lib/node/index.js:133:10)
    at Request.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/home/nodeproxy/MyLittleProxy/node_modules/minecraft-protocol/node_modules/superagent/lib/node/index.js:703:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

I'll fight with it, but that's my point for now.

**Comment by misiek08** [comment]
``` js
ready = false;
var oldremote = remoteclient;
var newremote = {
    host: server[0],
    port: server[1],
    online_mode: false,
    force_username: false,
    username: client.username,
};
var newremoteclient = mc.createClient(newremote);
newremoteclient.once('login', function (remoteclient, newremoteclient){
    console.log('Logged in');
    remoteclient = newremoteclient;
    console.log('Clients replaced');
    oldremote.end();
    ready = true;
});
```

This causes Minecraft to show: ![ss 2014-11-06 at 02 31 38](https://cloud.githubusercontent.com/assets/453110/4929550/ccf41908-6554-11e4-88e6-f24d0ab79937.png)
Packet that goes last to client is:

```
{ id: 24,
  entityId: 5021,
  x: -43186,
  y: 960,
  z: 1870,
  yaw: 0,
  pitch: -2 }
```

After that there is EPIPE.

**Comment by roblabla** [comment]
This isn't the one causing the crash. You're sending either a chat or kick packet containing malformed JSON data.

**Comment by misiek08** [comment]
I had few minutes to work on that again.
Here is dump.txt: https://gist.github.com/misiek08/24e470bc831e23929fdc

Error is same like above.
Code to switch server:

``` js
remoteclient.on('packet', function(packet) {
        if(switching) return;

        packet.destination = "local";
        if (!ready) {
            return;
        }
        writestream.write(JSON.stringify(packet) + "\n");


        // HANDLE SERVER SWITCHING
        if(packet.id == 0x3f)
        {
            if(packet.data.toString().substring(2, 9) == 'Connect')
            {
                var msg = {
                    translate: 'chat.type.announcement',
                    "with": [
                    'Probujesz sie polaczyc z: ',
                    packet.data.toString().substring(11)
                    ]
                };
                var server = servers[packet.data.toString().substring(11)];
                // client.write('chat', { message: JSON.stringify(msg) });
                var msg = {
                    translate: 'chat.type.announcement',
                    "with": [
                    'Teleport',
                    'IP: ' + server[0]+
                    ' Port:' + server[1]
                    ]
                };
                // client.write('chat', { message: JSON.stringify(msg) });

                switching = true;
                ready = false;

                var oldremote = remoteclient;
                var newremote = {
                    host: server[0],
                    port: 2571,
                    online_mode: false,
                    force_username: false,
                    username: client.username,
                };

                console.log('Assign new client');
                var newremoteclient = mc.createClient(newremote);
                console.log('New client assigned');
                newremoteclient.once('login', function (){
                    console.log('Logged in');
                    remoteclient = newremoteclient;
                    console.log('Clients replaced');
                    oldremote.end();
                    switching = false;
                    switched = true;
                    ready = true;
                });

                console.log('After scary part');
            }
            else
            {
                var msg = {
                    translate: 'chat.type.announcement',
                    "with": ['Nieznany PM: ', packet.data.toString().substring(0, 7)]
                };
                // client.write('chat', { message: JSON.stringify(msg) });
            }
        }
        client.write(packet.id, packet);
    });
```

I know that I should reset listeners on new client, but it looks like replacing remote client with new one keep listeners, so it's strange.

**Comment by misiek08** [comment]
Rewriting to:

``` js
console.log("Server listening on " + '0.0.0.0' + ":" + options.port);

server.on('login', function(client) {
    console.log("Logging in");

    // Whitelist
    for (var whitelistip in options.whitelistips) {
        if (whitelistip === client.socket.remoteAddress) {
            break;
        }
        client.end("You aren't whitelisted.");
        return;
    }

    if (options.remote.online_mode === false && !options.remote.force_username) {
        options.remote.username = client.username;
    }
    var ready = false;

    function onClientPacket(packet)
    {
        packet.destination = "remote";
        writestream.write(JSON.stringify(packet) + "\n");
        if (!ready) {
            return;
        }
        client.remoteclient.write(packet.id, packet);
    }

    function onRemotePacket(packet)
    {
        packet.destination = "local";
        if (!ready) {
            return;
        }
        writestream.write(JSON.stringify(packet) + "\n");


        // HANDLE SERVER SWITCHING
        if(packet.id == 0x3f)
        {
            if(packet.data.toString().substring(2, 9) == 'Connect')
            {
                var msg = {
                    translate: 'chat.type.announcement',
                    "with": [
                    'Probujesz sie polaczyc z: ',
                    packet.data.toString().substring(11)
                    ]
                };
                var server = servers[packet.data.toString().substring(11)];
                // client.write('chat', { message: JSON.stringify(msg) });
                var msg = {
                    translate: 'chat.type.announcement',
                    "with": [
                    'Teleport',
                    'IP: ' + server[0]+
                    ' Port:' + server[1]
                    ]
                };
                // client.write('chat', { message: JSON.stringify(msg) });

                ready = false;

                client.remoteclient.removeAllListeners();               
                client.remoteclient.end();

                var newremote = {
                    host: server[0],
                    port: 3501,
                    online_mode: false,
                    force_username: false,
                    username: client.username,
                };

                console.log('Assign new client');

                var newremoteclient = mc.createClient(newremote);
                client.remoteclient = newremoteclient;

                console.log('New client assigned');

                client.remoteclient.on('packet', function (packet){
                    onRemotePacket(packet);
                });

                client.remoteclient.once('login', function (){
                    console.log('Logged in');
                    ready = true;                   
                });

                console.log('After scary part');
            }
            else
            {
                var msg = {
                    translate: 'chat.type.announcement',
                    "with": ['Nieznany PM: ', packet.data.toString().substring(0, 7)]
                };
                // client.write('chat', { message: JSON.stringify(msg) });
            }
        }
        client.write(packet.id, packet);
    }

    function onRemoteEnd(reason)
    {
        client.end('[Remote] ' + reason);
    }

    function onClientEnd(reason)
    {
        client.remoteclient.end('[Local] ' + reason);
    }

    function onRemoteError(err)
    {       
        console.log('Error from remoteclient');
        console.error(err);
    }

    client.remoteclient = mc.createClient(options.remote);
    client.remoteclient.once('login', function() {
        ready = true;
        console.log("All clear !");
    });
    client.remoteclient.on('packet', function(packet) {
        onRemotePacket(packet);
    });
    client.on('packet', function(packet) {
        onClientPacket(packet);
    });
    client.remoteclient.on('error', function(err) {
        onRemoteError(err);
    });
    client.on('error', function(err) {
        console.log('Error from client');
        console.error(err);
    });
    client.remoteclient.on('end', function(reason) {
        onRemoteEnd(reason);
    });
    client.on('end', function(reason) {
        onClientEnd(reason);
    });
});

server.on('error', function(error) {
    console.log('Error:', error);
});
```

Console output: 

```
Creating server...
Server listening on 0.0.0.0:27565
Logging in
All clear !
Assign new client
New client assigned
After scary part
Logged in
```

dump.txt: https://gist.github.com/misiek08/de51d31b5a9a7fbd6821
made hanging MC on "Downloading terrain". Should I send any packet to any side to see the terrain on client?

**Comment by misiek08** [comment]
Any help?
